// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hawblysdepeeccylpapf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhd2JseXNkZXBlZWNjeWxwYXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDcxNzIsImV4cCI6MjA3MTc4MzE3Mn0.MTqnMbXNiUVhdvHUdgtXGYGR-cIsAojqr-KB9pldz1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});